{% set name = "seaborn-image" %}
{% set version = "0.10.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6dbb05205af975bf6a9fa286b07d26e62a7b27c93887c769d6c8fc402615f2a6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<3.13
    - matplotlib-base
    - matplotlib-scalebar
    - palettable
    - pooch
    - scikit-image >=0.17.2
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - seaborn_image

about:
  home: https://github.com/SarthakJariwala/seaborn-image
  summary: Attractive, descriptive and effective image visualization with seaborn-like API built on top of matplotlib
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SarthakJariwala
