{% set name = "seaborn-image" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8fb753f9ec5d70f9633e47ad910f18072e4882c7b6c31186bb1619f7cec9616b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.8,<3.11
  run:
    - python >=3.8,<3.11
    - importlib_metadata
    - matplotlib-base
    - matplotlib-scalebar
    - palettable
    - pooch
    - scikit-image >=0.17.2
    - scipy

test:
  imports:
    - seaborn_image

about:
  home: https://github.com/SarthakJariwala/seaborn-image
  summary: Attractive, descriptive and effective image visualization with seaborn-like API built on top of matplotlib
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - SarthakJariwala
